defmodule Alaja.Application do
  @moduledoc false

  use Application

  alias Alaja.{Config, Theme}

  @impl true
  def start(_type, _args) do
    # Load the on-disk alaja.conf into Application env BEFORE registering
    # the theme resolver. The resolver reads `:theme_active` from app env
    # at lookup time — if we don't load the conf first, every escript
    # starts with `:theme_active` set to the default atom `:default`,
    # ignoring whatever the user persisted via `alaja config theme set`.
    :ok = Config.ensure_loaded()

    # Bridge Pote's theme lookup to Alaja's active theme.
    #
    # Without this, `Pote.Orchestrator.parse_color("theme:<key>")` falls
    # back to Pote's hardcoded `@default_colors` palette, ignoring
    # whatever theme the user has selected with `alaja config theme set`.
    #
    # `Alaja.Theme` is generated by `use Pote.Theme` and reads the same
    # on-disk JSON files that `Alaja.Config` reads — both now share a
    # single source of truth.
    :ok = Theme.register_with_pote()

    children = []

    opts = [strategy: :one_for_one, name: Alaja.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
