defmodule Alaja.Application do
  @moduledoc """
  La aplicación OTP de Alaja.

  No aporta procesos: el arranque se limita a dejar el tema y la
  configuración en un estado conocido antes de que corra nada, porque
  varias piezas los leen en cuanto se las llama.

  ## Qué hace al arrancar

  1. `Alaja.Theme.Bootstrap.ensure_installed/0` — instala el directorio de
     temas si no existe. Es idempotente: sólo toca un `~/.config/alaja/`
     limpio.
  2. `Alaja.Config.ensure_loaded/0` — carga `alaja.conf` en el env de la
     aplicación. Va **antes** de registrar el resolutor de temas, que lee
     `:theme_active` de ahí; sin este orden, cada release arrancaría con
     el tema por defecto e ignoraría el que eligió el usuario con
     `alaja theme set`.
  3. `Alaja.Theme.register_with_pote/0` — conecta la búsqueda de tema de
     Pote con el tema activo de Alaja. Sin esto, un color escrito como
     `theme:<clave>` cae en la paleta fija de Pote.

  Después arranca un supervisor vacío, porque el estado vive en el
  proceso del cliente: los componentes son funciones puras que/devuelven
  nodios de vista.

  ## Por qué se documenta

  Estaba marcada `@moduledoc false` y desde fuera sólo se veía que
  `start/2` existía sin saber qué préparaba. Para un host como Acho, que
  arranca Alaja antes de nada, es parte de su arranque.
  """

  use Application

  alias Alaja.{Config, Theme}

  @impl true
  def start(_type, _args) do
    # Bootstrap the theme directory on first run. Idempotent — runs the
    # installer only on a clean `~/.config/alaja/`. Doing this here
    # (before `Config.ensure_loaded/0`) means every `mix test` (and
    # therefore `mix test --cover` in CI) starts with a populated
    # theme directory, regardless of the order in which tests run.
    :ok = Alaja.Theme.Bootstrap.ensure_installed()

    # Load the on-disk alaja.conf into Application env BEFORE registering
    # the theme resolver. The resolver reads `:theme_active` from app env
    # at lookup time — if we don't load the conf first, every release
    # starts with `:theme_active` set to the default atom `:default`,
    # ignoring whatever the user persisted via `alaja theme set`.
    :ok = Config.ensure_loaded()

    # Bridge Pote's theme lookup to Alaja's active theme.
    #
    # Without this, `Pote.Orchestrator.parse_color("theme:<key>")` falls
    # back to Pote's hardcoded `@default_colors` palette, ignoring
    # whatever theme the user has selected with `alaja theme set`.
    #
    # `Alaja.Theme` is generated by `use Pote.Theme` and reads the same
    # on-disk JSON files that `Alaja.Config` reads — both now share a
    # single source of truth.
    :ok = Theme.register_with_pote()

    children = []

    opts = [strategy: :one_for_one, name: Alaja.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
