defmodule Alaja.Theme do
  @moduledoc """
  Theme management facade for Alaja.

  Generated by `use Pote.Theme`. Exposes the full Pote.Theme contract
  — `list/0`, `active/0`, `activate/1`, `color/1`, `colors/0`,
  `install!/1`, `install_template/1`, `templates/0`,
  `register_with_pote/0` — wired up against the Alaja application's
  config + the `~/.config/alaja/themes` storage directory.

  ## Quick start

      Alaja.Theme.list()             # => ["default", "dracula", ...]
      Alaja.Theme.activate("dracula")
      Alaja.Theme.color("primary")   # => {189, 147, 249}

  ## Integration with Pote

  Calling `Alaja.Theme.register_with_pote/0` (or just `ensure_registered/0`,
  called lazily by every other function) registers a theme resolver on
  Pote's resolver stack so that `Pote.parse("theme:<key>")` consults the
  active Alaja theme. This is the mechanism that makes
  `alaja separator --color "theme:ternary"` resolve to the user's
  selected `ternary` colour, not a hardcoded default.
  """

  use Pote.Theme,
    config_app: :alaja,
    storage_dir: Path.join([System.user_home!(), ".config", "alaja", "themes"]),
    defaults: %{}
end
